version: '3.4'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 49001:8080
      - 50000:50000
    privileged: true
    volumes:
      - /opt/volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - proxy

networks: 
  proxy:
    external: true